#!/bin/bash

# General (Both)
general() {
    # misc
    pacaur -S cifs-utils gptfdisk imagemagick mediainfo perl-image-exiftool youtube-dl
    # hardware
    pacaur -S alsa-utils i7z intel-ucode ntfs-3g ntp pulseaudio-alsa wireless_tools
    # cli-apps
    pacaur -S irssi mpc mpd playerctl
    pacaur -S cli-visualizer htop-solarized ncmpcpp-git neofetch ranger-git
}

utils() {
    pacaur -Syy
    pacaur -S bc bind-tools colordiff iotop ntp openssh reflector sharutils sshfs unrar unzip
    pacaur -S fish tmux vim
}

xorg() {
    # xorg-apps
    pacaur -S autocutsel gimp gvfs lxappearance mirage nitrogen rofi rxvt-unicode rxvt-unicode-terminfo screenkey slop thunar thunar-volman tumbler vapoursynth vapoursynth-plugin-mvtools w3m xorg-xfd
    pacaur -S compton-git google-chrome i3-gaps mpv-vapoursynth nerd-fonts-git numlockx polybar-git obs-studio sublime-text-dev st unclutter-xfixes-git
    # themes
    pacaur -S arc-gtk-theme arc-icon-theme ttf-font-awesome ttf-dejavu ttf-mplus
}

# Laptop
x220() {
    pacaur -S libva-intel-driver libvdpau-va-gl 
}

# Desktop
chloe() {
    pacaur -S cpupower linux-headers nvidia nvidia-settings vdpauinfo
    pacaur -S ckb-next-git openrazer-meta polychromatic
}

# Server
neutron() {
    echo "Nothing here yet!"
    #pacaur -S 
}

fonts() {
    if [ ! -d "$HOME/.fonts/" ]; then
        mkdir $HOME/.fonts
    fi
    cp /usr/share/fonts/TTF/Knack* $HOME/.fonts/
    cp /usr/share/fonts/TTF/mplus-2p* $HOME/.fonts/
    pacaur -Rs ttf-mplus nerd-fonts-git
}

if [[ -z $1 ]]; then
    echo "Invalid argument: please specify which system (chloe/neutron/x220)"
    exit 1
fi
if [ "$1" == "chloe" ]; then
    utils
    general
    xorg
    chloe
    fonts
fi
if [ "$1" == "neutron" ]; then
    utils
    neutron
fi
if [ "$1" == "x220" ]; then
    utils
    general
    xorg
    x220
    fonts
fi
